"""Add file_path_transform

Revision ID: 755965a26437
Revises: e1d7311a4350
Create Date: 2024-04-27 10:10:01.970733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755965a26437'
down_revision: Union[str, None] = 'e1d7311a4350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('file_path_transform', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'file_path_transform')
    # ### end Alembic commands ###
