"""photo_tag change_5

Revision ID: 042bc1ac7b4f
Revises: b6cc80942831
Create Date: 2024-05-07 20:35:16.051346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042bc1ac7b4f'
down_revision: Union[str, None] = 'b6cc80942831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
