"""photo_tag change_3

Revision ID: 1668f37e89ce
Revises: a6d9bdcdd015
Create Date: 2024-05-07 20:21:39.918144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1668f37e89ce'
down_revision: Union[str, None] = 'a6d9bdcdd015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
