"""Change new

Revision ID: 7ff12911275b
Revises: 2126164ec42b
Create Date: 2024-04-30 22:53:19.822831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff12911275b'
down_revision: Union[str, None] = '2126164ec42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('photos', 'file_path_transform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'file_path_transform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('photos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
