"""photo_tag change_2

Revision ID: a6d9bdcdd015
Revises: cfde8bb07cb5
Create Date: 2024-05-07 20:15:36.843659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d9bdcdd015'
down_revision: Union[str, None] = 'cfde8bb07cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
