"""change models photo_tag

Revision ID: cfde8bb07cb5
Revises: ab7c64b6b256
Create Date: 2024-05-07 20:02:04.071430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfde8bb07cb5'
down_revision: Union[str, None] = 'ab7c64b6b256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
